name : workflow

on: 
    push:
    workflow_dispatch:
    schedule:
        - cron: '*/5 * * * *'


jobs: 
     echo:
        runs-on: ubuntu-latest
        steps: 
            - name: show the trigger
              run: echo "the name of the trigger is ${{ github.event_name }}"
